version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports: 
      - "80:80"
    links:
      - webapp
  webapp:
    build: .
    image: pistevga/galaxy-api
    env_file:
      - .env
    environment:
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - "5000:5000"
    container_name: "pistevga-galaxy-api"
