version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports: 
      - "80:80"
    links:
      - webapp
  webapp:
    build: .
    image: pistevga/galaxy-api
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - GALAXY_TABLE=${GALAXY_TABLE}
    ports:
      - "5000:5000"
    container_name: "pistevga-galaxy-api"
